config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    resources :comments
  end

  resources :about_mes

  root 'about_mes#index'

end

app/models/about_me.rb
class AboutMe < ActiveRecord::Base
has_attached_file :image
has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates_presence_of :post_id
  validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates_presence_of :body
end

app/controllers/about_mes_controller.rb
class AboutMesController < ApplicationController
  before_action :set_about_me, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "Balu", password: "Balus", except: [:index, :show]
  # GET /about_mes
  # GET /about_mes.json
  def index
    @about_mes = AboutMe.all
  end

  # GET /about_mes/1
  # GET /about_mes/1.json
  def show
  end

  # GET /about_mes/new
  def new
    @about_me = AboutMe.new
  end

  # GET /about_mes/1/edit
  def edit
  end

  # POST /about_mes
  # POST /about_mes.json
  def create
    @about_me = AboutMe.new(about_me_params)

    respond_to do |format|
      if @about_me.save
        format.html { redirect_to @about_me, notice: 'About me was successfully created.' }
        format.json { render :show, status: :created, location: @about_me }
      else
        format.html { render :new }
        format.json { render json: @about_me.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /about_mes/1
  # PATCH/PUT /about_mes/1.json
  def update
    respond_to do |format|
      if @about_me.update(about_me_params)
        format.html { redirect_to @about_me, notice: 'About me was successfully updated.' }
        format.json { render :show, status: :ok, location: @about_me }
      else
        format.html { render :edit }
        format.json { render json: @about_me.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /about_mes/1
  # DELETE /about_mes/1.json
  def destroy
    @about_me.destroy
    respond_to do |format|
      format.html { redirect_to about_mes_url, notice: 'About me was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about_me
      @about_me = AboutMe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_me_params
      params.require(:about_me).permit(:name, :tag, :greeting, :mylef, :sign, :image)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    #authentication
    def authenticate
      authenticate_or_request_with_http_basic do|name, password|
        name == "Balu" && password =="Balus"
      end
    end
end

app/helpers/about_mes_helper.rb
module AboutMesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about_mes/_form.html.erb
<div class="container editme" >
<%= form_for(@about_me) do |f| %>
  <% if @about_me.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@about_me.errors.count, "error") %> prohibited this about_me from being saved:</h2>

      <ul>
      <% @about_me.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tag %>:
    <%= f.text_field :tag %>
  </div>
  <div class="field">
    <%= f.label :greeting %>:
    <%= f.text_field :greeting %>
  </div>
  <div class="field">
    <%= f.text_area :mylef, :class => "tinymce", :rows => 20, :cols => 30 %>
  </div>
  <div class="field">
    <%= f.label :sign %>
    <%= f.text_field :sign %>
  </div>
  <div calss="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
<%= tinymce %>

app/views/about_mes/edit.html.erb
<%= render 'form' %>

<div class="container">
<%= link_to 'Show', @about_me %> |
<%= link_to 'Back', about_mes_path %>
</div>

app/views/about_mes/index.html.erb
<% @about_mes.each do |about_me| %>
  <div class="container" >
  <div id="top">
    <div id="topleft">
      <p> <%= image_tag about_me.image.url %> </p>
        </div>
        <div id="topright">
            <p class='name'>
              <strong><%= about_me.name %></strong><br>
              <lable id='tag'><%= about_me.tag %></label>
            </p>
            <p id='greeting'>
              <strong> <%= about_me.greeting %></strong>
            </p>

            <div>
              <%= about_me.mylef.html_safe %>
            </div >

            <p id='sign'>
              <%= about_me.sign %>
            </p>

            <%= link_to 'Edit', edit_about_me_path(about_me) %> |
            <%= link_to 'Back', about_mes_path %>
            <%= link_to 'New About me', new_about_me_path %>
        </div>
      </div>
    </div>
<% end %><br>

app/views/about_mes/new.html.erb
<h2 class="name container">Bala subrahmanyam</h2>
<h1>New about_me</h1>

<%= render 'form' %>

<%= link_to 'Back', about_mes_path %>

app/views/about_mes/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container" >
  <div id="top">
    <div id="topleft">
      <p> <%= image_tag @about_me.image.url %> </p>
    </div>
    <div id="topright">
        <p class='name'>
          <strong><%= @about_me.name %></strong><br>
          <lable id='tag'><%= @about_me.tag %></label>
        </p>
        <p id='greeting'>
          <strong> <%= @about_me.greeting %></strong>
        </p>

        <div>
          <%= @about_me.mylef.html_safe %>
        </div >

        <p id='sign'>
          <%= @about_me.sign %>
        </p>

        <%= link_to 'Edit', edit_about_me_path(@about_me) %> |
        <%= link_to 'Back', about_mes_path %>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <p>
    <strong>Posted <%= time_ago_in_words(comment.created_at) %></strong><br>
    <%= h(comment.body) %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment )) %>").fadeIn('slow');
$("#comments").prepend(new_comment);
$('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mysite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="titleclass">
  <h2 class="name container">Bala subrahmanyam</h2>
</div>

<%= yield %>
<div id="bottom">
    <button class="siteflow"><p><%= image_tag "aboutme.png" %></p><%= link_to 'AboutMe', about_mes_path %></button>
    <button class="siteflow"><p><%= image_tag "MyHistory.jpeg" %></p>My Journey sofar</button>
    <button class="siteflow"><p><%= image_tag "MyWork.jpeg" %></p>About my work</button>
    <button class="siteflow"><p><%= image_tag "MyBlogs.jpeg" %></p><%= link_to 'Blogs', posts_path %></button>
    <button class="siteflow"><p><%= image_tag "contact.jpg" %></p>Contacts</button>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<div class="container editme" >
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :class => "tinymce", :rows => 20, :cols => 30 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
<%= tinymce %>

app/views/posts/edit.html.erb
<h1 class="name container">Dude dont do mistakes again!</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container" >
  <div id="postdiv">
    <h3 class='postTitle'>All my blogs....</h3>

    <table>
      <thead>
        <tr>
          <th class='postTitle'>Title of the post</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.title %></td>
            <td><%= link_to 'Show', post %></td>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Post', new_post_path %>
  </div>
</div>

app/views/posts/new.html.erb
<h1 class="name container">Lets wakeup the world again...</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container" >
  <div id="postdiv">
      <p id="notice"><%= notice %></p>
      <p class='postTitle'>
        <strong>Title:</strong>
        <%= @post.title %>
      </p>

      <p id='postBody'>
        <%= @post.body.html_safe %>
      </p>

      <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Back', posts_path %>

      <h2> Comments </h2>
      <div id="comments">
        <%= render :partial => @post.comments.reverse %>
      </div>

      <%= form_for([@post, Comment.new], remote: true) do |newcoment| %>
        <p><%= newcoment.label :body, "New comment" %><br>
          <%= newcoment.text_area :body %>
        </p>
        <p><%= newcoment.submit "Add Comment"  %> </p>
      <% end %>
    </div>
  </div>
</div>